/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import java.awt.Color;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Owx
 */
public class schedule extends javax.swing.JPanel {

    private int month;
    private int year;
    String lecid;
    String selectedDateString;

    /**
     * Creates new form schedule
     */
    public schedule() {
        initComponents();
        function();
        setDate(lecid);
        
        //reload();

    }

    public void setMonth(int month) {
        this.month = month;
        setDate(lecid);
    }

    public void setYear(int year) {

        this.year = year;
        setDate(lecid);
    }

    public int getMonth() {
        return month;
    }

    public int getYear() {
        return year;
    }

    public void function() {
        mon.asTitle();
        tue.asTitle();
        wed.asTitle();
        thu.asTitle();
        fri.asTitle();
        //setDate();

    }

    public void setDate(String lecid) {

        // Set dates on the calendar
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month - 1);
        calendar.set(Calendar.DATE, 1);

        // Find the first Monday of the month
        while (calendar.get(Calendar.DAY_OF_WEEK) != Calendar.MONDAY) {
            calendar.add(Calendar.DATE, -1); // Move back one day until it's a Monday
        }
        
        

        ArrayList<String> scheduleList = test.getScheduleInfo();
        

        HashSet<String> uniqueDates = new HashSet<>();
        

        // Process schedule information
        for (String line : scheduleList) {
            String[] parts = line.split(";");
            String lcid = parts[0];
            if(lcid.equalsIgnoreCase(lecid)){
                
            String date = parts[1];
            
            // Add the formatted date to the HashSet for unique dates
            
            uniqueDates.add(date);
            }
        }

        // Iterate through the components (cells)
        for (Component com : getComponents()) {
            if (com instanceof time) {
                time time = (time) com;
                if (!time.isTitle()) {
                    // If the current day is Saturday or Sunday, skip to Monday
                    while (calendar.get(Calendar.DAY_OF_WEEK) == Calendar.SATURDAY || calendar.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY) {
                        calendar.add(Calendar.DATE, 1);
                    }

                    time.setText(calendar.get(Calendar.DATE) + "");
                    time.setDate(calendar.getTime());
                    time.currentMonth(calendar.get(Calendar.MONTH) == month - 1);

                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String formattedDate = dateFormat.format(calendar.getTime());
                    
                    

                    if (uniqueDates.contains(formattedDate)) {
                        

                        time.setBackground(Color.decode("#DCCECE"));
                    } else {
                        time.setBackground(Color.decode("#DFDFDF"));
                    }
                    
                    
                    
                   

                    calendar.add(Calendar.DATE, 1);
                }
            }
        }
    }
    

    

    private void reload() {
        ArrayList<String> projectList = test.getScheduleInfo();
        System.out.println(projectList);
    }

    public void refreshCalendar(String lecid) {
        setDate(lecid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mon = new presentation.time();
        tue = new presentation.time();
        wed = new presentation.time();
        thu = new presentation.time();
        fri = new presentation.time();
        time6 = new presentation.time();
        time7 = new presentation.time();
        time8 = new presentation.time();
        time9 = new presentation.time();
        time10 = new presentation.time();
        time11 = new presentation.time();
        time12 = new presentation.time();
        time13 = new presentation.time();
        time14 = new presentation.time();
        time15 = new presentation.time();
        time16 = new presentation.time();
        time17 = new presentation.time();
        time18 = new presentation.time();
        time19 = new presentation.time();
        time20 = new presentation.time();
        time21 = new presentation.time();
        time22 = new presentation.time();
        time23 = new presentation.time();
        time24 = new presentation.time();
        time25 = new presentation.time();
        time26 = new presentation.time();
        time27 = new presentation.time();
        time28 = new presentation.time();
        time29 = new presentation.time();
        time30 = new presentation.time();
        time31 = new presentation.time();
        time32 = new presentation.time();
        time33 = new presentation.time();
        time34 = new presentation.time();
        time35 = new presentation.time();

        setLayout(new java.awt.GridLayout(7, 5));

        mon.setText("Monday");
        add(mon);

        tue.setText("Tuesday");
        add(tue);

        wed.setText("Wednesday");
        add(wed);

        thu.setText("Thursday");
        add(thu);

        fri.setText("Friday");
        add(fri);
        add(time6);
        add(time7);
        add(time8);
        add(time9);
        add(time10);
        add(time11);
        add(time12);
        add(time13);
        add(time14);
        add(time15);
        add(time16);
        add(time17);
        add(time18);
        add(time19);
        add(time20);
        add(time21);
        add(time22);
        add(time23);
        add(time24);
        add(time25);
        add(time26);
        add(time27);
        add(time28);
        add(time29);
        add(time30);
        add(time31);
        add(time32);
        add(time33);
        add(time34);
        add(time35);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentation.time fri;
    private presentation.time mon;
    private presentation.time thu;
    private presentation.time time10;
    private presentation.time time11;
    private presentation.time time12;
    private presentation.time time13;
    private presentation.time time14;
    private presentation.time time15;
    private presentation.time time16;
    private presentation.time time17;
    private presentation.time time18;
    private presentation.time time19;
    private presentation.time time20;
    private presentation.time time21;
    private presentation.time time22;
    private presentation.time time23;
    private presentation.time time24;
    private presentation.time time25;
    private presentation.time time26;
    private presentation.time time27;
    private presentation.time time28;
    private presentation.time time29;
    private presentation.time time30;
    private presentation.time time31;
    private presentation.time time32;
    private presentation.time time33;
    private presentation.time time34;
    private presentation.time time35;
    private presentation.time time6;
    private presentation.time time7;
    private presentation.time time8;
    private presentation.time time9;
    private presentation.time tue;
    private presentation.time wed;
    // End of variables declaration//GEN-END:variables
}
