/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation;

import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashSet;

/**
 *
 * @author Owx
 */
public class schedule1 extends javax.swing.JPanel {
 private int month;
    private int year;
    String lecid;
    /**
     * Creates new form schedule1
     */
    public schedule1() {
        initComponents();
        function();
        setDate(lecid);
    }
    
    public void setMonth(int month) {
        this.month = month;
        setDate(lecid);
    }

    public void setYear(int year) {

        this.year = year;
        setDate(lecid);
    }

    public int getMonth() {
        return month;
    }

    public int getYear() {
        return year;
    }

    public void function() {
        mon.asTitle();
        tue.asTitle();
        wed.asTitle();
        thu.asTitle();
        fri.asTitle();
        //setDate();

    }

    public void setDate(String lecid) {

        // Set dates on the calendar
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month - 1);
        calendar.set(Calendar.DATE, 1);

        // Find the first Monday of the month
        while (calendar.get(Calendar.DAY_OF_WEEK) != Calendar.MONDAY) {
            calendar.add(Calendar.DATE, -1); // Move back one day until it's a Monday
        }
        
        

        ArrayList<String> scheduleList = test.getScheduleInfo();
        

        HashSet<String> uniqueDates = new HashSet<>();
        

        // Process schedule information
        for (String line : scheduleList) {
            String[] parts = line.split(";");
            String lcid = parts[0];
            if(lcid.equalsIgnoreCase(lecid)){
                
            String date = parts[1];
            
           
            uniqueDates.add(date);
            }
        }

        // Iterate through the components (cells)
        for (Component com : getComponents()) {
            if (com instanceof time1) {
                time1 time1 = (time1) com;
                if (!time1.isTitle()) {
                    // If the current day is Saturday or Sunday, skip to Monday
                    while (calendar.get(Calendar.DAY_OF_WEEK) == Calendar.SATURDAY || calendar.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY) {
                        calendar.add(Calendar.DATE, 1);
                    }

                    time1.setText(calendar.get(Calendar.DATE) + "");
                    time1.setDate(calendar.getTime());
                    time1.currentMonth1(calendar.get(Calendar.MONTH) == month - 1);

                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String formattedDate = dateFormat.format(calendar.getTime());
                    
                    

                    if (uniqueDates.contains(formattedDate)) {
                        

                        time1.setBackground(Color.decode("#769F85"));
                    } else {
                        time1.setBackground(Color.decode("#DFDFDF"));
                    }

                    calendar.add(Calendar.DATE, 1);
                }
            }
        }
    }

    private void reload() {
        ArrayList<String> projectList = test.getScheduleInfo();
        System.out.println(projectList);
    }

    public void refreshCalendar(String lecid) {
        setDate(lecid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mon = new presentation.time1();
        tue = new presentation.time1();
        wed = new presentation.time1();
        thu = new presentation.time1();
        fri = new presentation.time1();
        time16 = new presentation.time1();
        time17 = new presentation.time1();
        time18 = new presentation.time1();
        time19 = new presentation.time1();
        time20 = new presentation.time1();
        time21 = new presentation.time1();
        time22 = new presentation.time1();
        time23 = new presentation.time1();
        time24 = new presentation.time1();
        time25 = new presentation.time1();
        time26 = new presentation.time1();
        time27 = new presentation.time1();
        time28 = new presentation.time1();
        time29 = new presentation.time1();
        time30 = new presentation.time1();
        time31 = new presentation.time1();
        time32 = new presentation.time1();
        time33 = new presentation.time1();
        time34 = new presentation.time1();
        time35 = new presentation.time1();
        time36 = new presentation.time1();
        time37 = new presentation.time1();
        time38 = new presentation.time1();
        time39 = new presentation.time1();
        time40 = new presentation.time1();
        time41 = new presentation.time1();
        time42 = new presentation.time1();
        time43 = new presentation.time1();
        time44 = new presentation.time1();
        time45 = new presentation.time1();

        setLayout(new java.awt.GridLayout(7, 5));

        mon.setText("Monday");
        add(mon);

        tue.setText("Tuesday");
        add(tue);

        wed.setText("Wednesday");
        wed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wedActionPerformed(evt);
            }
        });
        add(wed);

        thu.setText("Thursday");
        add(thu);

        fri.setText("Friday");
        fri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friActionPerformed(evt);
            }
        });
        add(fri);
        add(time16);
        add(time17);
        add(time18);
        add(time19);
        add(time20);
        add(time21);
        add(time22);
        add(time23);
        add(time24);
        add(time25);
        add(time26);
        add(time27);
        add(time28);
        add(time29);
        add(time30);
        add(time31);
        add(time32);
        add(time33);
        add(time34);
        add(time35);
        add(time36);
        add(time37);
        add(time38);
        add(time39);
        add(time40);
        add(time41);
        add(time42);
        add(time43);
        add(time44);
        add(time45);
    }// </editor-fold>//GEN-END:initComponents

    private void wedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wedActionPerformed

    private void friActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentation.time1 fri;
    private presentation.time1 mon;
    private presentation.time1 thu;
    private presentation.time1 time16;
    private presentation.time1 time17;
    private presentation.time1 time18;
    private presentation.time1 time19;
    private presentation.time1 time20;
    private presentation.time1 time21;
    private presentation.time1 time22;
    private presentation.time1 time23;
    private presentation.time1 time24;
    private presentation.time1 time25;
    private presentation.time1 time26;
    private presentation.time1 time27;
    private presentation.time1 time28;
    private presentation.time1 time29;
    private presentation.time1 time30;
    private presentation.time1 time31;
    private presentation.time1 time32;
    private presentation.time1 time33;
    private presentation.time1 time34;
    private presentation.time1 time35;
    private presentation.time1 time36;
    private presentation.time1 time37;
    private presentation.time1 time38;
    private presentation.time1 time39;
    private presentation.time1 time40;
    private presentation.time1 time41;
    private presentation.time1 time42;
    private presentation.time1 time43;
    private presentation.time1 time44;
    private presentation.time1 time45;
    private presentation.time1 tue;
    private presentation.time1 wed;
    // End of variables declaration//GEN-END:variables
}
