/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;


public class CardPanel extends PanelShadow {
    public CardPanel() {
        initComponents();
        init();      
    }
    
    public void setData(CardModel data){
//        cardIcon.setIcon(data.getIcon());
        cardLabelName.setText(data.getTitle());
        cardValueLabel.setText(data.getValues());
    }
    
    private void init(){
        setRadius(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardLabelName = new javax.swing.JLabel();
        cardValueLabel = new javax.swing.JLabel();

        cardLabelName.setFont(new java.awt.Font("Bell MT", 1, 21)); // NOI18N
        cardLabelName.setForeground(new java.awt.Color(0, 51, 51));
        cardLabelName.setText("Name");

        cardValueLabel.setFont(new java.awt.Font("Bell MT", 1, 17)); // NOI18N
        cardValueLabel.setText("Values");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cardLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cardValueLabel)
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cardLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardValueLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardLabelName;
    private javax.swing.JLabel cardValueLabel;
    // End of variables declaration//GEN-END:variables
}
